NAME = Bureaucrat

SRC = main.cpp Bureaucrat.cpp Form.cpp
CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98
OBJ = $(SRC:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJ)
	$(CXX) $(CXXFLAGS) $(OBJ) -o $(NAME)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f  $(NAME)

re: fclean all 

.PHONY : all re clean fclean
